// The Alyeska compass mark. Inherits its color from `currentColor` so the same
// file works on the sand header, inside the teal menu button, on the login card
// and as the favicon, without a second version of it existing anywhere.
//
// The needle is one shape and no housing. The tinted west half is what makes it
// a needle rather than an arrowhead -- it reads as light falling on one side of
// a blade.
//
// It is drawn as a filled outline rather than a stroked path: an outer contour,
// an inner counter, and `fill-rule="evenodd"` to hollow it out. That is the only
// way to get all three points -- north and both tails -- genuinely sharp. A
// stroke rounds them (round joins) or spikes several units past the viewBox
// (miter joins), because the tail corners are far sharper angles than the apex
// and a single stroke cannot treat them differently. The counter is a 2.5-unit
// inward mitered offset of the outer contour, so the line weight stays even all
// the way around. Bare, the mark sits inside x 3.9-28.1, y 2.9-29.0.

// The needle at full size, and the two sizes the housed versions need. Any
// closed housing forces the needle to shrink until its tail points clear the
// rim: the tails reach 17.76 units from center, so a bezel whose innermost
// graduation sits at 13.9 leaves room for 72 percent and no more. These are
// measured rather than picked, which is why they are odd numbers.
const OUTLINE =
  "M16 2.9 28.1 29 16 20.9 3.9 29Z M16 8.84 9.92 21.96 16 17.89 22.08 21.96Z";
const WEST = "M9.92 21.96 16 17.89 16 8.84Z";

// Sixteen marks stepping inward from a rim at radius 15, north long and dark,
// the three other cardinals half-long. Generated by logo/housing.py, pasted
// rather than computed at render time -- it is the same sixteen every frame.
//
// There is deliberately no circle here. Every place large enough to want a
// graduated bezel already draws one (the round menu button), and a second ring
// three pixels inside the button's own rim reads as a mistake rather than as an
// instrument. The button's border is the bezel's edge; these are its numbers.
const BEZEL = [
  ["M16 3.7 16 1", 1.7, 0.72],
  ["M21.32 3.16 21.74 2.14", 1.0, 0.34],
  ["M25.83 6.17 26.61 5.39", 1.0, 0.34],
  ["M28.84 10.68 29.86 10.26", 1.0, 0.34],
  ["M29 16 31 16", 1.4, 0.44],
  ["M28.84 21.32 29.86 21.74", 1.0, 0.34],
  ["M25.83 25.83 26.61 26.61", 1.0, 0.34],
  ["M21.32 28.84 21.74 29.86", 1.0, 0.34],
  ["M16 29 16 31", 1.4, 0.44],
  ["M10.68 28.84 10.26 29.86", 1.0, 0.34],
  ["M6.17 25.83 5.39 26.61", 1.0, 0.34],
  ["M3.16 21.32 2.14 21.74", 1.0, 0.34],
  ["M3 16 1 16", 1.4, 0.44],
  ["M3.16 10.68 2.14 10.26", 1.0, 0.34],
  ["M6.17 6.17 5.39 5.39", 1.0, 0.34],
  ["M10.68 3.16 10.26 2.14", 1.0, 0.34],
];

/**
 * @param bezel  Draw the graduated bezel and shrink the needle to clear it.
 *               Only the menu dial asks for this; everywhere else the mark is
 *               either too small for graduations to survive or has no circle
 *               around it to act as the rim.
 * @param turned Swing the needle a quarter turn. The bezel does not move --
 *               on a real compass the card stays put and the needle points, and
 *               a rotating set of graduations would put north on the east mark.
 */
export default function AlyeskaMark({
  className = "h-7 w-7",
  bezel = false,
  turned = false,
}) {
  const scale = bezel ? 0.72 : 1;
  return (
    <svg
      viewBox="0 0 32 32"
      className={className}
      fill="none"
      aria-hidden="true"
    >
      {bezel &&
        BEZEL.map(([d, w, o]) => (
          <path
            key={d}
            d={d}
            stroke="currentColor"
            strokeWidth={w}
            strokeLinecap="round"
            opacity={o}
          />
        ))}
      <g
        style={{
          transform: `rotate(${turned ? 90 : 0}deg) scale(${scale})`,
          transformOrigin: "50% 50%",
          transition: "transform 200ms ease-out",
        }}
      >
        <path fillRule="evenodd" fill="currentColor" d={OUTLINE} />
        <path d={WEST} fill="currentColor" opacity="0.28" />
      </g>
    </svg>
  );
}
