// The Alyeska compass mark. Inherits its color from `currentColor` so the same
// file works on the sand header, inside the teal menu button, on the login card
// and as the favicon, without a second version of it existing anywhere.
//
// The needle is one shape and no housing. The tinted west half is what makes it
// a needle rather than an arrowhead -- it reads as light falling on one side of
// a blade.
//
// It is drawn as a filled outline rather than a stroked path: an outer contour,
// an inner counter, and `fill-rule="evenodd"` to hollow it out. That is the only
// way to get all three points -- north and both tails -- genuinely sharp. A
// stroke rounds them (round joins) or spikes several units past the viewBox
// (miter joins), because the tail corners are far sharper angles than the apex
// and a single stroke cannot treat them differently. The counter is a 2.5-unit
// inward mitered offset of the outer contour, so the line weight stays even all
// the way around. Bare, the mark sits inside x 3.9-28.1, y 2.9-29.0.

// The needle at full size, and the two sizes the housed versions need. Any
// closed housing forces the needle to shrink until its tail points clear the
// rim: the tails reach 17.76 units from center, so a bezel whose innermost
// graduation sits at 13.9 leaves room for 72 percent and no more. These are
// measured rather than picked, which is why they are odd numbers.
const OUTLINE =
  "M16 2.9 28.1 29 16 20.9 3.9 29Z M16 8.84 9.92 21.96 16 17.89 22.08 21.96Z";
const WEST = "M9.92 21.96 16 17.89 16 8.84Z";

// The default id for the aurora needle's gradient. Every aurora mark carries its
// own copy of the definition, and any mark that can share a page with another one
// passes its own id. See the `aurora` note below.
const AURORA_ID = "alyeska-aurora-needle";

// Sixteen marks stepping inward from a rim at radius 15, north long and dark,
// the three other cardinals half-long. Generated by logo/housing.py, pasted
// rather than computed at render time -- it is the same sixteen every frame.
//
// There is deliberately no circle here. Every place large enough to want a
// graduated bezel already draws one (the round menu button), and a second ring
// three pixels inside the button's own rim reads as a mistake rather than as an
// instrument. The button's border is the bezel's edge; these are its numbers.
const BEZEL = [
  ["M16 3.7 16 1", 1.7, 0.72],
  ["M21.32 3.16 21.74 2.14", 1.0, 0.34],
  ["M25.83 6.17 26.61 5.39", 1.0, 0.34],
  ["M28.84 10.68 29.86 10.26", 1.0, 0.34],
  ["M29 16 31 16", 1.4, 0.44],
  ["M28.84 21.32 29.86 21.74", 1.0, 0.34],
  ["M25.83 25.83 26.61 26.61", 1.0, 0.34],
  ["M21.32 28.84 21.74 29.86", 1.0, 0.34],
  ["M16 29 16 31", 1.4, 0.44],
  ["M10.68 28.84 10.26 29.86", 1.0, 0.34],
  ["M6.17 25.83 5.39 26.61", 1.0, 0.34],
  ["M3.16 21.32 2.14 21.74", 1.0, 0.34],
  ["M3 16 1 16", 1.4, 0.44],
  ["M3.16 10.68 2.14 10.26", 1.0, 0.34],
  ["M6.17 6.17 5.39 5.39", 1.0, 0.34],
  ["M10.68 3.16 10.26 2.14", 1.0, 0.34],
];

/**
 * @param bezel  Draw the graduated bezel and shrink the needle to clear it.
 *               Only the menu dial asks for this; everywhere else the mark is
 *               either too small for graduations to survive or has no circle
 *               around it to act as the rim.
 * @param compact  Hold the needle at the smaller size the bezel would have
 *               forced, even when the bezel itself is not drawn. Used by the
 *               menu dial when the search pill grows around the compass:
 *               the ring of tick marks would read as a second circle inside
 *               the pill, but if the needle sprang back to full size at the
 *               same moment the pill appeared, the compass would look like
 *               it jumped. This keeps the needle exactly where it was.
 * @param bezelColor  Paint the bezel graduations in a different color than
 *               the needle. Default is currentColor (both take the same
 *               ink). The menu dial hands in the pill's own border color
 *               while the search field is open, so the ticks read as an
 *               extension of the pill's rim curving inward around the
 *               compass rather than as a second circle inside the pill.
 * @param aurora Paint the needle as a fall from teal at north through glacier
 *               to plum at the tails, with the north graduation in amber.
 *               Every other surface takes its single ink from `currentColor`,
 *               which is what keeps one file working as a favicon, a menu
 *               button and a header mark at once. The sign-in screen is the
 *               one place with nothing else on it: there is no header to match
 *               and no colored button around the mark, so the instrument can
 *               carry the skin's own colors there without competing with
 *               anything, and the menu dial and Aly's own marks now do the same.
 *
 *               Each mark carries its own copy of the gradient inside its own
 *               svg. That is not tidiness: a reference resolves to whichever
 *               element holds the id first, and a paint server that happens to
 *               sit inside a hidden subtree is not reliably usable from a visible
 *               one -- Chrome drops it, and the needle vanishes rather than
 *               falling back to a color. So anything that can share a page with
 *               another mark passes `auroraId`.
 * @param auroraId Id for this mark's gradient. Only needs setting when two
 *               aurora marks can be on one page, which is every screen with the
 *               menu dial on it.
 * @param turned Swing the needle a quarter turn. The bezel does not move --
 *               on a real compass the card stays put and the needle points, and
 *               a rotating set of graduations would put north on the east mark.
 * @param spinning Continuously rotate the needle. Overrides `turned`. Used as
 *               a loading indicator: the same needle that points at things
 *               is now looking for one, which is a truer picture of what is
 *               happening than a separate spinner beside it would be.
 */
export default function AlyeskaMark({
  className = "h-7 w-7",
  bezel = false,
  compact = false,
  bezelColor = "currentColor",
  aurora = false,
  auroraId = AURORA_ID,
  turned = false,
  spinning = false,
}) {
  const scale = bezel || compact ? 0.72 : 1;
  const needle = aurora ? `url(#${auroraId})` : "currentColor";
  // The amber north graduation is dropped whenever the graduations have been
  // handed a color of their own. That happens in one place -- the menu dial
  // while the search pill is open, where the ticks are painted in the pill's
  // border color so they read as its rim curving inward. One amber mark in a
  // ring that is pretending to be the edge of something else would give the
  // trick away, and north is still obvious from the needle sitting on it.
  const northTick = aurora && bezelColor === "currentColor";
  return (
    <svg
      viewBox="0 0 32 32"
      className={className}
      fill="none"
      aria-hidden="true"
    >
      {aurora && (
        <defs>
          {/* Down the needle's own axis rather than the box: north is the point
              that means something on a compass, so the brightest color belongs
              there and the tails fall away from it. */}
          <linearGradient
            id={auroraId}
            x1="16"
            y1="2.9"
            x2="16"
            y2="29"
            gradientUnits="userSpaceOnUse"
          >
            <stop offset="0" stopColor="var(--aurora-north)" />
            <stop offset="0.55" stopColor="var(--aurora-mid)" />
            <stop offset="1" stopColor="var(--aurora-tail)" />
          </linearGradient>
        </defs>
      )}
      {bezel &&
        BEZEL.map(([d, w, o], index) => (
          <path
            key={d}
            d={d}
            stroke={
              northTick && index === 0 ? "var(--aurora-north-tick)" : bezelColor
            }
            strokeWidth={w}
            strokeLinecap="round"
            opacity={northTick && index === 0 ? 1 : o}
          />
        ))}
      <g
        className={spinning ? "alyeska-mark-drift" : undefined}
        style={
          spinning
            ? {
                // The spin runs on its own keyframes; scale is applied to the
                // element itself, and the CSS animation carries the rotation.
                // Cannot combine an inline transform with a CSS animation that
                // sets transform without the animation overwriting the scale,
                // so the CSS rule includes the scale via a CSS variable.
                transformOrigin: "50% 50%",
                ["--alyeska-mark-scale"]: scale,
              }
            : {
                transform: `rotate(${turned ? 90 : 0}deg) scale(${scale})`,
                transformOrigin: "50% 50%",
                transition: "transform 200ms ease-out",
              }
        }
      >
        <path fillRule="evenodd" fill={needle} d={OUTLINE} />
        <path
          d={WEST}
          fill={aurora ? "var(--aurora-tail)" : "currentColor"}
          opacity={aurora ? 0.3 : 0.28}
        />
      </g>
    </svg>
  );
}
