"use client";

// What the family looks at for the first half-second of a cold open.
//
// Opening the app used to show a white flash, then a frame of grey bars, then
// covers snapping in one at a time -- three separate arrivals, which is what
// read as frozen. This holds one thing over the whole page instead: the compass
// drawing itself on the page's own ground, with the wordmark under it. When the
// app underneath is ready the veil lifts away, so the first real thing anybody
// sees is a whole page rather than a half-built one.
//
// Three rules it has to keep:
//
//   It must be in the very first frame of HTML, before any JavaScript has run.
//   That is why the markup lives in the layout and is hidden by CSS rather than
//   unmounted by React -- a veil that waited for hydration would be behind the
//   blank moment it exists to cover.
//
//   It must never flicker. On a warm open the app can be ready in 80ms, and a
//   splash that appeared and vanished inside a tenth of a second is worse than
//   none, so it is held for HOLD_MS whatever happens.
//
//   It must never trap anybody. If this component never mounts -- a bundle that
//   failed, JavaScript switched off -- the stylesheet lifts the veil on its own
//   after five seconds. That fail-safe is in globals.css, not here, because the
//   whole point is that it works when this file does not.
//
// Under the wordmark it says "Travel" and turns one word: personalized,
// contextualized, simplified. Those are the three promises in the order they
// are earned -- who is travelling, what the trip actually is, and what that
// saves them -- and they turn on CSS alone, so they animate in the first frame
// rather than waiting for React.
//
// It is shown once per document load. Moving between tabs afterwards never
// brings it back: the flag lives on <html>, and the layout is not re-rendered
// by a client-side navigation.

import { useEffect } from "react";

// Shortest time the mark stays up: one full turn of the tagline, three words at
// 1.9s each. It was 620ms, chosen so a fast open stayed fast, which meant the
// rotation was a thing only a slow connection ever saw. Holding for the whole
// turn is a deliberate trade -- every open now costs the family five and a half
// seconds they did not previously spend -- and it is the reason the words get
// long enough on screen to be read as claims rather than as a spinner.
const HOLD_MS = 5700;

// Longest. Past this the page is shown whatever state it is in, because a veil
// held over a screen that is never going to finish is just a hidden error. It
// has to sit above HOLD_MS with room to spare, and below the stylesheet's
// fail-safe, or one of the three would be quietly overruling another.
const CAP_MS = 7200;

// The four cardinal marks: path, stroke width, opacity, dash length for the
// draw, and the stagger. Radius 15, north long and dark. Generated by
// logo/housing.py.
const CARDINALS = [
  ["M16 1 16 4.6", 1.6, 0.66, 4, 0],
  ["M31 16 28.2 16", 1.3, 0.38, 3, 130],
  ["M16 31 16 28.2", 1.3, 0.38, 3, 260],
  ["M1 16 3.8 16", 1.3, 0.38, 3, 390],
];

// The shipped needle, stepped down to 86 percent so its tail points pass
// between the cardinal marks rather than into them. The tint on the west face
// arrives with the rest of it rather than separately -- it is one object.
function Needle({ className }) {
  return (
    <g transform="translate(16 16) scale(0.86) translate(-16 -16)">
      <g className={className}>
        <path
          fillRule="evenodd"
          fill="currentColor"
          d="M16 2.9 28.1 29 16 20.9 3.9 29Z M16 8.84 9.92 21.96 16 17.89 22.08 21.96Z"
        />
        <path
          d="M9.92 21.96 16 17.89 16 8.84Z"
          fill="currentColor"
          opacity="0.28"
        />
      </g>
    </g>
  );
}

export default function BootVeil() {
  useEffect(() => {
    const root = document.documentElement;
    if (root.dataset.booted) return;

    let done = false;
    const lift = () => {
      if (done) return;
      done = true;
      root.dataset.booted = "1";
    };

    const cap = setTimeout(lift, CAP_MS);

    // Two frames after mount is the earliest the browser has actually painted
    // what hydration produced, and the fonts matter because lifting onto text
    // that is about to reflow into Fraunces undoes the point of the hold.
    const ready = Promise.all([
      new Promise((go) =>
        requestAnimationFrame(() => requestAnimationFrame(go)),
      ),
      document.fonts?.ready ?? Promise.resolve(),
    ]);

    let wait = null;
    ready.then(() => {
      // performance.now() is milliseconds since the navigation started, which
      // is the moment the family pressed the icon -- the only anchor worth
      // measuring the hold from.
      const left = Math.max(0, HOLD_MS - performance.now());
      wait = setTimeout(lift, left);
    });

    return () => {
      clearTimeout(cap);
      if (wait) clearTimeout(wait);
    };
  }, []);

  return (
    <div id="boot-veil" aria-hidden="true">
      <div className="boot-mark">
        <svg viewBox="0 0 32 32" fill="none">
          {/* The finished mark, faint and still, under the one that arrives. The
              first frame of a stroke animation is an empty box, and a splash
              whose first quarter-second is blank is the problem this is meant to
              solve -- so the shape is whole from the start and the animation
              lands on top of it. */}
          <g className="boot-ghost">
            {CARDINALS.map(([d, w]) => (
              <path
                key={d}
                d={d}
                stroke="currentColor"
                strokeWidth={w}
                strokeLinecap="round"
              />
            ))}
            <Needle />
          </g>
          {/* Four marks instead of a ring. They are drawn from the rim inward,
              north first and then east, south, west, which is the order anybody
              reads a compass in -- and having them arrive in sequence rather
              than together is what makes the half-second feel like an
              instrument settling instead of a logo fading up. */}
          {CARDINALS.map(([d, w, o, len, delay]) => (
            <path
              key={d}
              className="boot-stroke"
              d={d}
              stroke="currentColor"
              strokeWidth={w}
              strokeLinecap="round"
              opacity={o}
              style={{ "--len": len, animationDelay: `${delay}ms` }}
            />
          ))}
          {/* The needle cannot be drawn the way a stroke can -- it is a filled
              outline, which is the whole reason its three points are sharp -- so
              it grows into place instead, landing as the last mark closes. */}
          <Needle className="boot-needle" />
        </svg>
        <span className="boot-word font-display">Alyeska</span>
        {/* The tagline turns on CSS keyframes rather than a React interval, for
            the same reason the veil is markup in the layout: this has to be
            animating in the first frame of HTML, before any JavaScript has run.
            An interval would start its first swap after hydration -- which on
            the open this exists to cover is the moment the veil is already
            lifting.

            Three words at 1.9s each, and the veil is now held for the whole
            turn rather than the other way round -- a rotation nobody stays
            long enough to see is not worth having, and a word that leaves
            before it has been read is a spinner with letters on it. */}
        <p className="boot-tag" aria-hidden="true">
          <span className="boot-tag-fixed">Travel</span>
          <span className="boot-tag-slot">
            <span>personalized.</span>
            <span>contextualized.</span>
            <span>simplified.</span>
          </span>
        </p>
      </div>
    </div>
  );
}
