/**
 * The words a beta tester is shown before they are let in, and the versions
 * those words are known by.
 *
 * They live here rather than in the screen that draws them for the same reason
 * the pledge does: the same paragraphs are read twice -- once at the gate, and
 * again from Settings by somebody deciding whether to take an answer back -- and
 * a promise that reads two ways is not one.
 *
 * Changing any wording that changes what is being agreed to means bumping
 * AGREEMENT_VERSION. Every stored consent still naming the old version stops
 * matching, and those testers walk the screens again on their next navigation.
 * Fixing a typo does not deserve that; adding a data category does.
 */

// Bump when the agreement's meaning changes. Dates rather than numbers so it is
// obvious from a database row when a tester agreed to what.
export const AGREEMENT_VERSION = "2026-09-13";

// Bump when the privacy policy changes. Kept apart from the agreement because
// the two are reissued for different reasons and a tester should not be walked
// through a liability waiver again because a retention period moved.
export const PRIVACY_VERSION = "2026-09-13";

// The processor named on the AI screen, in the words the tester is shown. Stored
// alongside their answer, so if this ever changes the old consent cannot be
// mistaken for consent to the new one.
export const AI_PROVIDER = "Google Gemini API";

// The build a consent was recorded against, so a bug report and a consent
// record can be lined up against the same software.
export const APP_BUILD = process.env.NEXT_PUBLIC_APP_BUILD || "0.9.4 (312)";

// When these builds stop working. Said out loud on the first screen, because a
// tester who is surprised by an expiry reads it as the app breaking.
export const BETA_ENDS = "December 12, 2026";

// Where the two documents live inside the app. Used by every link the app itself
// draws, because an absolute link to the production host from a preview build
// takes a tester out of the build they are testing and into a different one.
export const PRIVACY_PATH = "/privacy";
export const TERMS_PATH = "/beta-terms";

// The same two pages said absolutely, for the store listings and for the places
// where a URL is printed as text rather than linked. Both have to be reachable
// from outside the app, on a plain non-geofenced URL with no sign-in.
export const PRIVACY_URL =
  process.env.NEXT_PUBLIC_PRIVACY_URL || "https://alyeska.app/privacy";
export const TERMS_URL =
  process.env.NEXT_PUBLIC_TERMS_URL || "https://alyeska.app/beta-terms";
// The one address a tester is told to write to, and the same one the privacy
// policy prints for deletion and access requests, so it has to be a mailbox
// somebody actually opens rather than a plausible-looking alias.
export const SUPPORT_EMAIL =
  process.env.NEXT_PUBLIC_SUPPORT_EMAIL || "admin@alyeska.app";

/**
 * The agreement itself, in plain language.
 *
 * Written to be read on a phone by somebody who wants to start using the app,
 * which is the only audience it will ever have. Every section is short enough
 * that skipping it is a choice rather than a necessity.
 */
export const AGREEMENT = [
  {
    id: "unfinished",
    heading: "This is unfinished software",
    body: "Alyeska is in beta. Screens change without notice, features appear and disappear, and things break. Do not rely on it as the only place a booking, a document, or a plan is written down.",
  },
  {
    id: "data-loss",
    heading: "Your data may be lost",
    body: "Beta databases get migrated, reset, and occasionally restored from a backup that is hours old. Keep your own copy of anything you would be upset to lose, especially passports, visas, and confirmations.",
  },
  {
    id: "no-warranty",
    heading: "No warranty",
    body: "The app is provided as is, without warranty of any kind. Nothing in it is a guarantee that a flight time is right, a border rule is current, or a document is where you left it.",
  },
  {
    id: "liability",
    heading: "Limit of liability",
    body: "To the fullest extent the law allows, we are not liable for indirect, incidental, or consequential losses arising from your use of the beta, including a missed connection, a canceled reservation, or a trip that cost more than the app estimated. Where liability cannot be excluded, it is limited to the amount you have paid us, which during the beta is nothing.",
  },
  {
    id: "not-advice",
    heading: "Aly is not an adviser",
    body: "Aly's suggestions are generated by an AI model and can be confidently wrong. Visa requirements, entry rules, medical guidance, insurance terms, and money matters must be checked against the airline, the consulate, the insurer, or a professional before you act on them.",
  },
  {
    id: "your-content",
    heading: "What you put in stays yours",
    body: "Your trips, documents, photos, and notes remain yours. You grant us only the permission needed to run the service for you: to store your content, show it to the members of your household, and pass the relevant parts to the providers listed on the next screens.",
  },
  {
    id: "feedback",
    heading: "Feedback becomes ours",
    body: "Bug reports, suggestions, survey answers, and anything you tell us about how the app should work are given freely and become ours to use, build, and ship without payment, credit, or obligation. This covers your feedback about the product. It does not cover your trips, your documents, or your family's information, which stay yours under the section above.",
  },
  {
    id: "confidentiality",
    heading: "Keep the unreleased parts to yourself",
    body: "The beta builds, unreleased features, prices under discussion, and screens you see before anyone else are confidential. Do not post screenshots publicly, write them up, or show them to anyone outside your household without asking us first. You may tell people the app exists and that you are testing it.",
  },
  {
    id: "no-reverse",
    heading: "What not to do",
    body: "Do not attempt to work around access controls, read other households' data, load malware, resell access, or use the app to break the law. We can end your access at any time, for any reason, without notice.",
  },
  {
    id: "ending",
    heading: "Ending your part in it",
    body: `You can stop at any time. Deleting your account in Settings removes your household's data on our side within 30 days, other than records the law requires us to keep. The beta itself ends ${BETA_ENDS}, when these builds stop working. Withdrawing consent for AI processing keeps your account and turns Aly off.`,
  },
  {
    id: "changes",
    heading: "Changes to this agreement",
    body: "If what you are agreeing to changes, you will be shown the new version and asked again before you can carry on. We will not quietly treat an old acceptance as agreement to something new.",
  },
  {
    id: "law",
    heading: "Governing law",
    body: "This agreement is governed by the laws of the State of Missouri, United States, without regard to its conflict-of-laws rules.",
  },
  {
    id: "contact",
    heading: "Reaching us",
    body: `Questions, deletion requests, and anything you want on the record: ${SUPPORT_EMAIL}. The full terms are at ${TERMS_URL} and the privacy policy is at ${PRIVACY_URL}.`,
  },
];

/**
 * What the app collects, why, and how long it keeps it.
 *
 * The order is how close it sits to the person: their own account first, then
 * their household, then the things the app reaches out and reads, then what it
 * gathers about itself. `review` marks a category a human at our end can read
 * while the beta runs, which is the part of a beta nobody expects and everybody
 * should be told.
 */
export const DATA_CATEGORIES = [
  {
    id: "account",
    title: "Account and profile",
    what: "Your name, email address, sign-in method, and the preferences you set.",
    why: "To keep you signed in, to know which household is yours, and to draw the app the way you set it.",
    kept: "Until you delete your account.",
    review: false,
  },
  {
    id: "household",
    title: "Household members",
    what: "The people and animals you add: names, ages or birth dates, dietary notes, and travel preferences.",
    why: "So plans, packing, and Aly's suggestions fit the family actually going rather than an average one.",
    kept: "Until you remove the person or delete your account.",
    review: false,
  },
  {
    id: "email",
    title: "Booking email",
    what: "Confirmation emails you forward to your household's inbox address, and the flights, stays, and reservations read out of them.",
    why: "So a forwarded confirmation becomes an itinerary entry without anybody typing it in.",
    kept: "The parsed booking stays with the trip. The original message is discarded after 30 days.",
    review: true,
  },
  {
    id: "documents",
    title: "Travel documents",
    what: "Passports, visas, insurance certificates, tickets, and anything else you upload, along with the fields read out of them.",
    why: "So they are on your phone when a border agent asks and there is no signal.",
    kept: "Until you delete the document or the account.",
    review: false,
  },
  {
    id: "location",
    title: "Location",
    what: "Your device's approximate location, only while a screen that uses it is open.",
    why: "For distances, local weather, and what is near you today. Never tracked in the background.",
    kept: "Used for the answer and not stored.",
    review: false,
  },
  {
    id: "assistant",
    title: "Conversations with Aly",
    what: "What you ask her, what she answers, and the trip context sent with the question.",
    why: "So she remembers the thread, and so we can see what she gets wrong.",
    kept: "90 days, then deleted.",
    review: true,
  },
  {
    id: "diagnostics",
    title: "Beta diagnostics",
    what: "Crash reports, error messages, screen timings, and which features you opened.",
    why: "To find what is broken and what nobody can figure out how to use.",
    kept: "90 days, then deleted. Can be turned off below and in Settings.",
    review: true,
  },
];

/**
 * The optional parts, each of which the app has a working shape without.
 *
 * Asked at the gate rather than sprung later, and every one of them starts off.
 * `without` is the honest answer to "so what happens if I say no", which is the
 * question a permission prompt with two buttons and no explanation refuses to
 * answer.
 */
export const OPTIONAL_FEATURES = [
  {
    id: "mail",
    title: "Read forwarded confirmations",
    detail:
      "Your household gets its own inbox address. Anything you forward there is parsed into the trip.",
    without: "Add flights and stays by hand.",
  },
  {
    id: "notifications",
    title: "Reminders before they matter",
    detail:
      "A note the evening before about check-in, a passport about to expire, or a booking that needs confirming.",
    without: "Check the Reminders screen yourself.",
  },
  {
    id: "location",
    title: "Use where you are",
    detail:
      "Distances, weather, and what is nearby, worked out while the screen is open.",
    without: "Type a place name instead.",
  },
  {
    id: "documents",
    title: "Read fields from documents",
    detail:
      "Passport numbers, expiry dates, and confirmation codes pulled out of what you upload so you do not type them twice.",
    without: "The file is stored and shown as you uploaded it.",
  },
  {
    id: "calendar",
    title: "Add trips to your calendar",
    detail:
      "A subscription link your calendar app reads, so the itinerary shows up next to the rest of your week.",
    without: "Read the itinerary in the app.",
  },
];

/**
 * What the AI screen has to say before it asks. Kept as data so the same list
 * appears at the gate and in Settings without being written twice.
 */
export const AI_DISCLOSURE = {
  sent: [
    "Your question, and the trip it was asked about",
    "Names, ages, and preferences of the travelers on that trip",
    "Dates, destinations, and bookings relevant to the question",
  ],
  notSent: [
    "Your passwords or sign-in credentials",
    "Uploaded document files",
    "Photos, unless you attach one to a question",
    "Anything belonging to another household",
  ],
  terms: [
    `Processing happens on ${AI_PROVIDER} servers in the United States.`,
    "Under the paid API terms, your content is not used to train their models.",
    "They keep prompts up to 30 days for abuse monitoring, then delete them.",
  ],
};
