-- What each answer cost, in the only unit Google bills in.
--
-- Until now the app kept no record of its own model spend. There was a table for
-- refusals, so we could say why an answer had not been searched, and a table for
-- screen visits, so we could say where people went -- and nothing at all for the
-- one number on the invoice. The honest answer to "which feature is the bill" was
-- a reading of the code and a count of rows, which puts the ranking of features
-- inside an argument rather than inside a query.
--
-- One row per call to the model, written wherever that call was made from: a
-- question to Aly, a look for tips, a document read, a trip cover. A single turn
-- can therefore write several rows, and that is the point -- the chat route asks
-- more than once on some turns, a grounded look falls back to an ungrounded one,
-- and a model that answers 200 with nothing in it is billed and then asked again.
-- Each of those is a separate row, so the doubling shows up as rows rather than
-- having to be inferred.
--
-- No prompt, no reply, no travel detail: counts, a model name, a feature name and
-- a clock. Nothing here describes a family or a trip, which is why it can be kept
-- for as long as a bill needs explaining without widening what the app stores
-- about anybody.

create table if not exists public.model_usage (
  id bigint generated by default as identity primary key,
  at timestamptz not null default now(),
  -- Whose call it was. Null only for the developer harness, which has no
  -- household; a background job names the household it is acting for.
  user_id uuid references auth.users (id) on delete cascade,
  -- Which part of the app spent this, in the app's own words: chat.answer,
  -- tips.trip, wallet.offers, cover.draw, document.read.
  feature text not null,
  provider text not null default 'gemini',
  model text not null,
  -- Google's own search, attached to the request and billed separately from the
  -- tokens. searches is how many it actually ran, which is not the same thing:
  -- the tool can be available and go unused.
  grounded boolean not null default false,
  searches integer not null default 0,
  -- Where this attempt sat in the ladder for one call. Zero is the first model
  -- asked; anything above it was paid for after something else had failed.
  attempt integer not null default 0,
  status integer,
  finish_reason text,
  -- Whether anything usable came back. A 200 with no words and no tool call is
  -- billed exactly like an answer and is the reason this column exists.
  ok boolean not null default true,
  prompt_tokens integer,
  candidates_tokens integer,
  thoughts_tokens integer,
  cached_tokens integer,
  tool_tokens integer,
  total_tokens integer,
  ms integer
);

comment on table public.model_usage is
  'One row per model call: token counts, model, feature and clock. No prompt or reply text is stored.';
comment on column public.model_usage.feature is
  'The part of the app that spent this, in dotted form: chat.answer, tips.trip, cover.draw.';
comment on column public.model_usage.attempt is
  'Position in the ladder for one call. Above zero means an earlier model had already been paid for.';
comment on column public.model_usage.ok is
  'False for a reply with no words and no tool call, which is billed like any other.';

-- The three questions this table exists to answer: what did the month cost, which
-- feature cost it, and which model.
create index if not exists model_usage_at_idx on public.model_usage (at desc);
create index if not exists model_usage_feature_idx on public.model_usage (feature, at desc);
create index if not exists model_usage_model_idx on public.model_usage (model, at desc);

alter table public.model_usage enable row level security;

-- Same shape as agent_refusals: a person may write and read their own rows, and
-- nothing else. The background jobs write with the service key, which is outside
-- these policies by design, and the admin screens read with it too.
drop policy if exists model_usage_own_insert on public.model_usage;
create policy model_usage_own_insert on public.model_usage
  for insert to authenticated
  with check (auth.uid() = user_id);

drop policy if exists model_usage_own_select on public.model_usage;
create policy model_usage_own_select on public.model_usage
  for select to authenticated
  using (auth.uid() = user_id);
